export const ROUTES = {
  root: "/",
  404: "*",
  login: "/login",
  dashboard: "/dashboard",
  company: "/company",
  companySetting: "/company-setting",
  companyUsers: "/company/:companyId/user",
  user: "/user",
  customer: "/customer",
  customerDashboard: "/customer/dashboard",
  dailyReport: "/report",
  fingerPrint: "/trash",
  imageUpload: "/uploads",
};
